export const OPEN_SIDEBAR = "OPEN_SIDEBAR";
export const CLOSE_SIDEBAR = "CLOSE_SIDEBAR";
export const PRODUCTS_LOADING = "PRODUCTS_LOADING";
export const PRODUCTS_LOADED = "PRODUCTS_LOADED";
export const PRODUCTS_ERROR = "PRODUCTS_ERROR";
export const SINGLE_PRODUCT_LOADING = "SINGLE_PRODUCT_LOADING";
export const SINGLE_PRODUCT_LOADED = "SINGLE_PRODUCT_LOADED";
export const SINGLE_PRODUCT_ERROR = "SINGLE_PRODUCT_ERROR";
