export const OPEN_SIDEBAR = "OPEN_SIDEBAR";
export const CLOSE_SIDEBAR = "CLOSE_SIDEBAR";
export const PRODUCTS_LOADING = "PRODUCTS_LOADING";
export const PRODUCTS_LOADED = "PRODUCTS_LOADED";
export const PRODUCTS_ERROR = "PRODUCTS_ERROR";
